export const headerData = [
  { id: 1, categoryName: "국내", type: "korea" },
  { id: 2, categoryName: "해외", type: "overseas" },
  { id: 3, categoryName: "정보", type: "information" },
  { id: 4, categoryName: "기타", type: "other" },
];

export const listData = [
  {
    id: 1,
    // link: "/order",
    link: "/",
    path: "/assets/images/list-gnb-01.png",
    listName: "바로주문",
    type: "order",
  },
  {
    id: 2,
    link: "/menu",
    path: "/assets/images/list-gnb-02.png",
    listName: "메뉴",
    type: "menu",
  },
  {
    id: 3,
    // link: "/store",
    link: "/",
    path: "/assets/images/list-gnb-03.png",
    listName: "매장",
    type: "store",
  },
  {
    id: 4,
    // link: "/event",
    link: "/",
    path: "/assets/images/list-gnb-04.png",
    listName: "이벤트",
    type: "event",
  },
  {
    id: 5,
    // link: "/mypage",
    link: "/",
    path: "/assets/images/list-gnb-05.png",
    listName: "마이미피",
    type: "mypage",
  },
];

export const dcSlideList = [
  {
    id: 1,
    link: "/discount",
    discountName: "생일기념",
    discount: "20%",
  },
  {
    id: 2,
    link: "/discount",
    discountName: "방문포장 최대",
    discount: "30%",
  },
  {
    id: 3,
    link: "/discount",
    discountName: "현대카드 M포인트",
    discount: "50%",
  },
  {
    id: 4,
    link: "/discount",
    discountName: "신규회원 가입시",
    discount: "20%",
  },
  {
    id: 5,
    link: "/discount",
    discountName: "회원정보 수정시",
    discount: "20%",
  },
];

export const btnList = [
  {
    id: 1,
    link: "/menu",
    type: "menu",
    btnName: "모두보기",
  },
  {
    id: 2,
    link: "/menu/pizza",
    type: "pizza",
    btnName: "피자",
  },
  {
    id: 3,
    link: "/menu/simplePizza",
    type: "simplePizza",
    btnName: "1인용피자",
  },
  {
    id: 4,
    link: "/menu/salad",
    type: "salad",
    btnName: "샐러드&사이드",
  },
];

export const pizzaList = [
  {
    id: 1,
    path: "/assets/images/pizza/pizza-01.jpeg",
    type: "pizza",
    pizzaName: "멕시칸 하바네로 피자 세트",
    priceR: 22900,
    priceL: 27900,
    desc: "멕시칸 하바네로 피자+코울슬로+하바네로마요소스",
  },
  {
    id: 2,
    path: "/assets/images/pizza/pizza-02.jpeg",
    type: "pizza",
    pizzaName: "햄벅한새우",
    priceR: 27900,
    priceL: 35900,
    desc: "치즈 햄버거와 마요 콘새우의 행복한 맛남",
  },
  {
    id: 3,
    path: "/assets/images/pizza/pizza-03.jpeg",
    type: "pizza",
    pizzaName: "미스터트리오",
    priceR: 27900,
    priceL: 35900,
    desc: "멕시칸 하바네로 피자+코울슬로+하바네로마요소스",
  },
  {
    id: 4,
    path: "/assets/images/pizza/pizza-04.jpeg",
    type: "pizza",
    pizzaName: "치즈블라썸스테이크",
    priceR: 28500,
    priceL: 36500,
    desc: "와인숙성 스테이크와 6가지 치즈의 해피엔딩",
  },
  {
    id: 5,
    path: "/assets/images/pizza/pizza-05.jpeg",
    type: "pizza",
    pizzaName: "새우천왕",
    priceR: 27900,
    priceL: 35900,
    desc: "해물 토핑의 레전드 킹새우와 고기 토핑의 제왕 소불고기의 뜨거운 한판승부!",
  },
  {
    id: 6,
    path: "/assets/images/pizza/pizza-06.jpeg",
    type: "pizza",
    pizzaName: "쉬림프 골드",
    priceR: 27900,
    priceL: 35900,
    desc: "스파이시 통새우가 아낌없이 올라가 씹을수록 탱글탱글한 식감에 매콤한 칠리소스의 화려한 조화가 환상적인 맛!",
  },

  {
    id: 7,
    path: "/assets/images//simple-pizza/simple-pizza01.jpeg",
    type: "simplePizza",
    pizzaName: "멕시칸샌드",
    priceR: 4900,
    priceL: 7900,
  },
  {
    id: 8,
    path: "/assets/images//simple-pizza/simple-pizza02.jpeg",
    type: "simplePizza",
    pizzaName: "쉬골샌드",
    priceR: 4900,
    priceL: 7900,
  },
  {
    id: 9,
    path: "/assets/images//simple-pizza/simple-pizza03.jpeg",
    type: "simplePizza",
    pizzaName: "불고기샌드",
    priceR: 4900,
    priceL: 7900,
  },
  {
    id: 10,
    path: "/assets/images//simple-pizza/simple-pizza04.jpeg",
    type: "simplePizza",
    pizzaName: "포골샌드",
    priceR: 4900,
    priceL: 7900,
  },
  {
    id: 11,
    path: "/assets/images//simple-pizza/simple-pizza05.jpeg",
    type: "simplePizza",
    pizzaName: "멕시칸샌드세트",
    priceR: 6500,
    priceL: 7900,
  },
  {
    id: 12,
    path: "/assets/images//simple-pizza/simple-pizza06.jpeg",
    type: "simplePizza",
    pizzaName: "쉬골샌드세트",
    priceR: 6500,
    priceL: 8900,
  },

  {
    id: 13,
    path: "/assets/images//salad/salad-01.jpeg",
    type: "salad",
    pizzaName: "홈샐러드",
    priceR: 5900,
    priceL: 7900,
  },
  {
    id: 14,
    path: "/assets/images//salad/salad-02.jpeg",
    type: "salad",
    pizzaName: "케이준치킨 샐러드",
    priceR: 6900,
    priceL: 7900,
  },
  {
    id: 15,
    path: "/assets/images//salad/salad-03.jpeg",
    type: "salad",
    pizzaName: "국내산 오이 피클",
    priceR: 500,
    priceL: 1000,
  },
  {
    id: 16,
    path: "/assets/images//salad/salad-04.jpeg",
    type: "salad",
    pizzaName: "갈릭디핑소스",
    priceR: 100,
    priceL: 1000,
  },
  {
    id: 17,
    path: "/assets/images//salad/salad-05.jpeg",
    type: "salad",
    pizzaName: "핫 소스",
    priceR: 100,
    priceL: 1000,
  },
  {
    id: 18,
    path: "/assets/images//salad/salad-06.jpeg",
    type: "salad",
    pizzaName: "허니머스타드 소스",
    priceR: 100,
    priceL: 1000,
  },
];
